import './style.css'
import './node_modules/bootstrap/dist/css/bootstrap.min.css'
import './src/scripts/calculos/eficienciaOperativa'
import './src/components/calculadoraEficiencia'
import './src/components/manoDeObra'
import './src/scripts/calculos/mano de obra/thisMain'
import './src/scripts/materiaPrima/agregarApi'
import './src/scripts/materiaPrima/registro'
import './src/scripts/productos/registro'
import './src/scripts/costosIndirectos/registro'
import './src/scripts/costosIndirectos/agregarApi'
import './src/scripts/prendasMokapi'
import './src/scripts/prendasMokapi'
import './src/scripts/costosIndirectos/gastosMP'

